export const allUsers = {
    students: [
      {
        name: "Sanya Modi",
        degree: "BTech CSE",
        batch: "2025",
        imageUrl:
          "https://plus.unsplash.com/premium_photo-1690407617542-2f210cf20d7e?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        skills: ["React", "MongoDB", "Node.js"],
        projects: ["Netflix Clone", "E-Commerce Platform", "Portfolio Website"],
        category: "student",
      },
      {
        name: "Aarav Mehta",
        degree: "BTech IT",
        batch: "2026",
        imageUrl: "https://randomuser.me/api/portraits/men/32.jpg",
        skills: ["Python", "Django", "Machine Learning"],
        projects: ["Chatbot AI", "Stock Prediction", "Task Manager App"],
        category: "student",
      },
      {
        name: "Aarav Mehta",
        degree: "BTech IT",
        batch: "2026",
        imageUrl: "https://randomuser.me/api/portraits/men/32.jpg",
        skills: ["Python", "Django", "Machine Learning"],
        projects: ["Chatbot AI", "Stock Prediction", "Task Manager App"],
        category: "student",
      },
      {
        name: "Aarav Mehta",
        degree: "BTech IT",
        batch: "2026",
        imageUrl: "https://randomuser.me/api/portraits/men/32.jpg",
        skills: ["Python", "Django", "Machine Learning"],
        projects: ["Chatbot AI", "Stock Prediction", "Task Manager App"],
        category: "student",
      },
    ],
    alumni: [
      {
        name: "Riya Sharma",
        position: "AI Researcher",
        company: "Google",
        batch: "2020",
        imageUrl: "https://randomuser.me/api/portraits/women/45.jpg",
        skills: ["Deep Learning", "TensorFlow", "OpenCV"],
        experience: ["Facial Recognition", "AI Image Enhancer", "Pose Estimation"],
        category: "alumni",
      },
      {
        name: "Kabir Joshi",
        position: "Embedded Systems Engineer",
        company: "Intel",
        batch: "2019",
        imageUrl: "https://randomuser.me/api/portraits/men/40.jpg",
        skills: ["Embedded Systems", "IoT", "Arduino"],
        experience: [
          "Smart Home Automation",
          "IoT Weather Station",
          "RFID Door Lock",
        ],
        category: "alumni",
      },
    ],
    mentors: [
      {
        name: "Meera Kapoor",
        position: "Senior Full Stack Developer",
        company: "Microsoft",
        batch: "N/A",
        imageUrl: "https://randomuser.me/api/portraits/women/37.jpg",
        skills: ["Full Stack", "Next.js", "GraphQL"],
        experience: ["Blog CMS", "Task Manager", "E-learning Platform"],
        category: "mentor",
      },
      {
        name: "Vikram Singh",
        position: "Data Science Lead",
        company: "Amazon",
        batch: "2015",
        imageUrl: "https://randomuser.me/api/portraits/men/50.jpg",
        skills: ["Data Science", "Pandas", "Big Data"],
        experience: [
          "Fraud Detection System",
          "Data Analytics Dashboard",
          "AI Chatbot",
        ],
        category: "mentor",
      },
    ],
  };
