const mentors = [
  {
    name: "John Doe",
    program: "Career Guidance Program",
    company: "Tech Corp",
    position: "Senior Software Engineer",
    expertise: ["JavaScript", "React", "Node.js"],
    imageUrl: "https://via.placeholder.com/80",
  },
  {
    name: "Jane Smith",
    program: "Leadership Mentorship",
    company: "Innovate Inc",
    position: "Product Manager",
    expertise: ["Product Management", "Agile", "UX Design"],
    imageUrl: "https://via.placeholder.com/80",
  },
  {
    name: "John Doe",
    program: "Career Guidance Program",
    company: "Tech Corp",
    position: "Senior Software Engineer",
    expertise: ["JavaScript", "React", "Node.js"],
    imageUrl: "https://via.placeholder.com/80",
  },
  {
    name: "Jane Smith",
    program: "Leadership Mentorship",
    company: "Innovate Inc",
    position: "Product Manager",
    expertise: ["Product Management", "Agile", "UX Design"],
    imageUrl: "https://via.placeholder.com/80",
  },
  {
    name: "John Doe",
    program: "Career Guidance Program",
    company: "Tech Corp",
    position: "Senior Software Engineer",
    expertise: ["JavaScript", "React", "Node.js"],
    imageUrl: "https://via.placeholder.com/80",
  },
  {
    name: "Jane Smith",
    program: "Leadership Mentorship",
    company: "Innovate Inc",
    position: "Product Manager",
    expertise: ["Product Management", "Agile", "UX Design"],
    imageUrl: "https://via.placeholder.com/80",
  },
  {
    name: "John Doe",
    program: "Career Guidance Program",
    company: "Tech Corp",
    position: "Senior Software Engineer",
    expertise: ["JavaScript", "React", "Node.js"],
    imageUrl: "https://via.placeholder.com/80",
  },
  {
    name: "Jane Smith",
    program: "Leadership Mentorship",
    company: "Innovate Inc",
    position: "Product Manager",
    expertise: ["Product Management", "Agile", "UX Design"],
    imageUrl: "https://via.placeholder.com/80",
  },
  {
    name: "John Doe",
    program: "Career Guidance Program",
    company: "Tech Corp",
    position: "Senior Software Engineer",
    expertise: ["JavaScript", "React", "Node.js"],
    imageUrl: "https://via.placeholder.com/80",
  },
  {
    name: "Jane Smith",
    program: "Leadership Mentorship",
    company: "Innovate Inc",
    position: "Product Manager",
    expertise: ["Product Management", "Agile", "UX Design"],
    imageUrl: "https://via.placeholder.com/80",
  },
  {
    name: "John Doe",
    program: "Career Guidance Program",
    company: "Tech Corp",
    position: "Senior Software Engineer",
    expertise: ["JavaScript", "React", "Node.js"],
    imageUrl: "https://via.placeholder.com/80",
  },
  {
    name: "Jane Smith",
    program: "Leadership Mentorship",
    company: "Innovate Inc",
    position: "Product Manager",
    expertise: ["Product Management", "Agile", "UX Design"],
    imageUrl: "https://via.placeholder.com/80",
  },
  {
    name: "John Doe",
    program: "Career Guidance Program",
    company: "Tech Corp",
    position: "Senior Software Engineer",
    expertise: ["JavaScript", "React", "Node.js"],
    imageUrl: "https://via.placeholder.com/80",
  },
  {
    name: "Jane Smith",
    program: "Leadership Mentorship",
    company: "Innovate Inc",
    position: "Product Manager",
    expertise: ["Product Management", "Agile", "UX Design"],
    imageUrl: "https://via.placeholder.com/80",
  },
];
export default mentors;