const jobs = [
    {
      id: 1,
      title: "Frontend Developer",
      company: "Google",
      location: "Remote",
      salary: "$120,000 - $150,000",
      type: "Full-time",
      posted: "2 days ago",
      description: "Develop UI using React.js, TypeScript, and Tailwind CSS.",
      requirements: [
        "3+ years experience with React.js",
        "Strong knowledge of JavaScript & TypeScript",
        "Experience with Tailwind CSS and modern UI frameworks",
      ],
    },
    {
      id: 2,
      title: "Backend Engineer",
      company: "Amazon",
      location: "New York, NY",
      salary: "$130,000 - $160,000",
      type: "Full-time",
      posted: "1 week ago",
      description: "Build scalable backend systems using Node.js and AWS.",
      requirements: [
        "5+ years experience with Node.js",
        "Experience with AWS Lambda, DynamoDB, and microservices",
        "Strong understanding of database management (SQL & NoSQL)",
      ],
    },
    {
      id: 3,
      title: "Data Scientist",
      company: "Meta",
      location: "San Francisco, CA",
      salary: "$140,000 - $180,000",
      type: "Full-time",
      posted: "3 days ago",
      description: "Analyze data and build ML models for user insights.",
      requirements: [
        "4+ years experience with Python, TensorFlow, and Pandas",
        "Experience in data visualization and statistical analysis",
        "Strong understanding of machine learning algorithms",
      ],
    },
    {
      id: 4,
      title: "UI/UX Designer",
      company: "Spotify",
      location: "Berlin, Germany",
      salary: "$90,000 - $120,000",
      type: "Contract",
      posted: "5 days ago",
      description: "Design intuitive and beautiful user experiences.",
      requirements: [
        "3+ years experience in UI/UX design",
        "Proficiency in Figma, Sketch, or Adobe XD",
        "Understanding of user behavior and usability testing",
      ],
    },
    {
      id: 5,
      title: "DevOps Engineer",
      company: "Netflix",
      location: "Los Angeles, CA",
      salary: "$150,000 - $190,000",
      type: "Full-time",
      posted: "2 weeks ago",
      description: "Implement CI/CD pipelines and manage cloud infrastructure.",
      requirements: [
        "5+ years experience in DevOps & Cloud computing",
        "Expertise in Kubernetes, Docker, and CI/CD tools",
        "Strong scripting skills in Bash, Python, or Terraform",
      ],
    },
    {
      id: 6,
      title: "Cybersecurity Analyst",
      company: "Microsoft",
      location: "Washington, D.C.",
      salary: "$110,000 - $140,000",
      type: "Full-time",
      posted: "4 days ago",
      description: "Monitor and secure network systems from threats.",
      requirements: [
        "3+ years experience in cybersecurity",
        "Familiarity with penetration testing and vulnerability assessment",
        "Strong knowledge of firewalls, IDS/IPS, and SIEM tools",
      ],
    },
    {
      id: 7,
      title: "AI Engineer",
      company: "OpenAI",
      location: "San Francisco, CA",
      salary: "$160,000 - $200,000",
      type: "Full-time",
      posted: "6 days ago",
      description: "Develop AI models and optimize deep learning networks.",
      requirements: [
        "Experience with TensorFlow, PyTorch, and NLP models",
        "Knowledge of reinforcement learning and generative AI",
        "Strong understanding of AI ethics and optimization techniques",
      ],
    },
    {
      id: 8,
      title: "Product Manager",
      company: "Apple",
      location: "Cupertino, CA",
      salary: "$140,000 - $170,000",
      type: "Full-time",
      posted: "1 month ago",
      description: "Lead cross-functional teams to build innovative products.",
      requirements: [
        "Strong leadership and strategic thinking skills",
        "Experience in product lifecycle management",
        "Understanding of Agile methodologies and market research",
      ],
    },
    {
      id: 9,
      title: "Full Stack Developer",
      company: "Tesla",
      location: "Austin, TX",
      salary: "$130,000 - $160,000",
      type: "Full-time",
      posted: "3 weeks ago",
      description: "Work on web and mobile apps for vehicle systems.",
      requirements: [
        "Experience with MERN stack (MongoDB, Express, React, Node)",
        "Knowledge of GraphQL and REST APIs",
        "Proficiency in Docker, Kubernetes, and cloud services",
      ],
    },
    {
      id: 10,
      title: "Software Engineer",
      company: "Twitter",
      location: "Remote",
      salary: "$115,000 - $140,000",
      type: "Full-time",
      posted: "2 days ago",
      description: "Develop scalable APIs and backend services.",
      requirements: [
        "Proficiency in Golang, Python, or Ruby",
        "Experience with distributed systems and cloud platforms",
        "Familiarity with caching strategies and message queues",
      ],
    },
    {
      id: 11,
      title: "Blockchain Developer",
      company: "Coinbase",
      location: "Remote",
      salary: "$140,000 - $175,000",
      type: "Full-time",
      posted: "2 weeks ago",
      description: "Develop secure blockchain applications and smart contracts.",
      requirements: [
        "Experience with Solidity and Ethereum blockchain",
        "Understanding of cryptography and consensus algorithms",
        "Familiarity with DeFi protocols and Web3 development",
      ],
    },
    {
      id: 12,
      title: "Game Developer",
      company: "Epic Games",
      location: "Cary, NC",
      salary: "$110,000 - $150,000",
      type: "Full-time",
      posted: "3 days ago",
      description: "Develop next-gen games using Unreal Engine 5.",
      requirements: [
        "Proficiency in C++ and game development frameworks",
        "Experience with Unreal Engine or Unity",
        "Knowledge of multiplayer networking and physics engines",
      ],
    },
    {
      id: 13,
      title: "Cloud Engineer",
      company: "IBM",
      location: "New York, NY",
      salary: "$125,000 - $155,000",
      type: "Full-time",
      posted: "5 days ago",
      description: "Deploy and manage cloud infrastructure at scale.",
      requirements: [
        "Experience with AWS, Azure, or Google Cloud",
        "Strong scripting skills in Python or Bash",
        "Knowledge of serverless computing and cloud security",
      ],
    },
    {
      id: 14,
      title: "Marketing Manager",
      company: "Adobe",
      location: "San Jose, CA",
      salary: "$100,000 - $130,000",
      type: "Full-time",
      posted: "3 weeks ago",
      description: "Lead digital marketing campaigns and brand strategies.",
      requirements: [
        "Experience in SEO, PPC, and content marketing",
        "Strong analytical and creative thinking skills",
        "Proficiency in marketing automation tools",
      ],
    },
    {
      id: 15,
      title: "IT Support Specialist",
      company: "Dell",
      location: "Austin, TX",
      salary: "$80,000 - $100,000",
      type: "Full-time",
      posted: "1 month ago",
      description: "Provide technical support and IT solutions.",
      requirements: [
        "Experience in troubleshooting hardware and software issues",
        "Familiarity with Active Directory and IT ticketing systems",
        "Strong customer service and communication skills",
      ],
    },
  ];
  
  export default jobs;
  